//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class EARLY_WARNING_COUNTRIES
    {
        public string PUBLISHTIME { get; set; }
        public string WARNING_CATAGRAY { get; set; }
        public string WARNING_LEVEL { get; set; }
        public string REGION_INFLUENCE { get; set; }
        public string DURATION_INFLUENCE { get; set; }
        public string WARNING_CONTENT { get; set; }
        public Nullable<System.DateTime> INSERTTIME { get; set; }
        public string COUNTRY { get; set; }
        public string DOWNURL { get; set; }
        public string ENDSERVICE { get; set; }
        public Nullable<System.DateTime> SERVERTIME { get; set; }
        public string QIANFAREN { get; set; }
        public string ISNEW { get; set; }
        public Nullable<decimal> FID { get; set; }
        public string FGUID { get; set; }
    }
}
