//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoWens
    {
        public BaoWens()
        {
            this.BwYbs = new HashSet<BwYbs>();
        }
    
        public System.Guid BWID { get; set; }
        public string FileName { get; set; }
        public string Content { get; set; }
        public string YBUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> YBDateTime { get; set; }
        public string BWType { get; set; }
        public Nullable<System.Guid> YBUserID { get; set; }
        public Nullable<bool> IsTranslate { get; set; }
    
        public virtual YbUsers YbUsers { get; set; }
        public virtual ICollection<BwYbs> BwYbs { get; set; }
    }
}
