//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BwYbs
    {
        public System.Guid BWYBID { get; set; }
        public string YBUserName { get; set; }
        public Nullable<System.DateTime> YBDateTime { get; set; }
        public string YBType { get; set; }
        public string BWFileName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<decimal> TianQiCode241 { get; set; }
        public Nullable<decimal> TianQiCode242 { get; set; }
        public string TianQiName241 { get; set; }
        public string TianQiName242 { get; set; }
        public Nullable<decimal> MinTemp24 { get; set; }
        public Nullable<decimal> MaxTemp24 { get; set; }
        public Nullable<decimal> TianQiCode481 { get; set; }
        public Nullable<decimal> TianQiCode482 { get; set; }
        public string TianQiName481 { get; set; }
        public string TianQiName482 { get; set; }
        public Nullable<decimal> MinTemp48 { get; set; }
        public Nullable<decimal> MaxTemp48 { get; set; }
        public Nullable<decimal> TianQiCode721 { get; set; }
        public Nullable<decimal> TianQiCode722 { get; set; }
        public string TianQiName721 { get; set; }
        public string TianQiName722 { get; set; }
        public Nullable<decimal> MinTemp72 { get; set; }
        public Nullable<decimal> MaxTemp72 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> BWID { get; set; }
        public Nullable<System.Guid> YBUserID { get; set; }
    
        public virtual BaoWens BaoWens { get; set; }
        public virtual YbUsers YbUsers { get; set; }
    }
}
