//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Z
    {
        public System.Guid FileID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string FileName { get; set; }
        public string FileContent { get; set; }
        public Nullable<decimal> Twenty_Eight { get; set; }
        public Nullable<decimal> Eight_Twenty { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
    }
}
