//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score_Month
    {
        public System.Guid ScoreID { get; set; }
        public string YBUserName { get; set; }
        public Nullable<decimal> RainShine { get; set; }
        public Nullable<decimal> MinTemp { get; set; }
        public Nullable<decimal> MaxTemp { get; set; }
        public Nullable<decimal> Rainfall { get; set; }
        public Nullable<decimal> Rainstorm { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> WeightedTotal { get; set; }
        public Nullable<decimal> RainShine_Group { get; set; }
        public Nullable<decimal> MinTemp_Group { get; set; }
        public Nullable<decimal> MaxTemp_Group { get; set; }
        public Nullable<decimal> Rainfall_Group { get; set; }
        public Nullable<decimal> Rainstorm_Group { get; set; }
        public Nullable<decimal> Total_Group { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.Guid> YBUserID { get; set; }
    
        public virtual YbUsers YbUsers { get; set; }
    }
}
