//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score_Day
    {
        public System.Guid ScoreID { get; set; }
        public Nullable<System.DateTime> YBDate { get; set; }
        public string YBTime { get; set; }
        public string YBUserName { get; set; }
        public Nullable<System.Guid> YBUserID { get; set; }
        public Nullable<int> RainShine24 { get; set; }
        public Nullable<int> MaxTemp24 { get; set; }
        public Nullable<int> MinTemp24 { get; set; }
        public Nullable<int> RainShine48 { get; set; }
        public Nullable<int> MaxTemp48 { get; set; }
        public Nullable<int> MinTemp48 { get; set; }
        public Nullable<int> RainShine72 { get; set; }
        public Nullable<int> MaxTemp72 { get; set; }
        public Nullable<int> MinTemp72 { get; set; }
        public Nullable<int> AllTotal { get; set; }
        public Nullable<int> Rainfall24 { get; set; }
        public Nullable<int> Rainfall24Total { get; set; }
        public Nullable<int> Rainfall48 { get; set; }
        public Nullable<int> Rainfall48Total { get; set; }
        public Nullable<int> Rainfall72 { get; set; }
        public Nullable<int> Rainfall72Total { get; set; }
        public Nullable<int> Rainstorm24 { get; set; }
        public Nullable<int> Rainstorm24Total { get; set; }
        public Nullable<int> Rainstorm48 { get; set; }
        public Nullable<int> Rainstorm48Total { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual YbUsers YbUsers { get; set; }
    }
}
