//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarnInfo
    {
        public System.Guid InfoID { get; set; }
        public string Content { get; set; }
        public string WarnCategory { get; set; }
        public string WarnLevel { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
