//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarnCheck
    {
        public System.Guid CheckID { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public string WarningCategory { get; set; }
        public string WarningLevel { get; set; }
        public Nullable<System.DateTime> ReachTime { get; set; }
        public Nullable<int> ReachSpendMinute { get; set; }
        public string Accuracy { get; set; }
        public string Remark { get; set; }
        public string ReachStation { get; set; }
        public Nullable<decimal> ReachValue { get; set; }
    }
}
