//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarnStatistics
    {
        public System.Guid StatisticsID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string WarnCategory { get; set; }
        public string WarnLevel { get; set; }
        public Nullable<int> TSScore { get; set; }
        public Nullable<int> HitRate { get; set; }
        public Nullable<int> MissRate { get; set; }
        public Nullable<int> EmptyRate { get; set; }
        public Nullable<int> ReachSpendMinute1 { get; set; }
        public Nullable<int> ReachSpendMinute2 { get; set; }
        public Nullable<int> ReachSpendMinute3 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LevelOrder { get; set; }
    }
}
