//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YBPFDB_Entities : DbContext
    {
        public YBPFDB_Entities()
            : base("name=YBPFDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaoWens> BaoWens { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<YbUsers> YbUsers { get; set; }
        public DbSet<BwYbs> BwYbs { get; set; }
        public DbSet<WeatherDictionary> WeatherDictionary { get; set; }
        public DbSet<LiveData> LiveData { get; set; }
    }
}
