//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PF.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YbUsers
    {
        public YbUsers()
        {
            this.BaoWens = new HashSet<BaoWens>();
            this.BwYbs = new HashSet<BwYbs>();
        }
    
        public System.Guid YBUserID { get; set; }
        public string YBUserName { get; set; }
    
        public virtual ICollection<BaoWens> BaoWens { get; set; }
        public virtual ICollection<BwYbs> BwYbs { get; set; }
    }
}
